### ISSUE TITLE
Design database schema for image

### ISSUE THREAD

**Issue by jamestang12** [Who-put-that-in-my-drive/Moments#9]
- [x] Discuss design with the team
- [x] Create documentations for the schema

**Comment by jamestang12** [comment]
@patel1643

**Comment by Mwpereira** [comment]
As per discussion on discord - 
{
    "id": String, //uuid,
    "title": String,
    "size": String,
    "caption": String,
    "tags": String, //String Array
    "categories": String, //String Array,
    "ownerId": String, //Email,
    "location": String,
    "lastModifiedDateTime": number,
    "uploadedDateTime": number,
}
